version: '2'
services:
  #https://hub.docker.com/_/redis
  rabbitmq:
      image: redis:5.0.4
      restart: always
      ports:
        - 6379:6379
  gateway:
    image: spring-cloud/consul-gateway
    ports:
      - "8900:8900"
  auth-service:
    image: spring-cloud/consul-auth-service
    ports:
      - "8001:8001"
  #https://hub.docker.com/r/kennedyoliveira/hystrix-dashboard
  hystrix:
    image: kennedyoliveira/hystrix-dashboard
    ports:
      - "7979:7979"
  #https://hub.docker.com/r/openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  
  
  service-a:
    image: spring-cloud/consul-service-a
    ports:
      - "8901:8901"
  service-b:
    image: spring-cloud/consul-service-b
    ports:
      - "8902:8902"