server:
  port: 8901
  
msg: testing_hello

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #默认：（方法上记得要加上@HystrixCommand，否则无效）
#          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true 
              
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  #https://github.com/spring-cloud/spring-cloud-security/issues/61
  http:
    client:
      enabled: true  

spring:
#  rabbitmq:
#    host: 10.0.0.5
#    port: 5672
#    username: test
#    password: test123
  sleuth:
    sampler:
      percentage: 1
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
    web:
      client:
        enabled: true #web开启sleuth功能
      
  zipkin:
    base-url: http://${ZIPKIN_SERVER:zipkin-server}:9411      

#totally customized vars
#not solved, https://github.com/spring-cloud/spring-cloud-security/issues/61
authserver:
    #hostname: auth-service
    hostname: ${AUTH_SERVER:auth-service}
    port: 8001
    contextPath: 

#https://docs.spring.io/spring-security-oauth2-boot/docs/current-SNAPSHOT/reference/htmlsingle/
security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
      #prefer-token-info: true # Use the token info, can be set to false to use the user info.

#HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        #include: hystrix.stream, info, health
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
      #base-path: actuator //by default

turbine:
  app-config: consul-service-a,consul-service-b
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream  
    
logging:
  level:
    root: INFO
    org.springframework: INFO   