server:
  #context-path: /uaa #2.0 abandoned
  port: 8001
  servlet:
    context-path: 

spring:

  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER:192.168.28.8}:${MYSQL_SERVER_PORT:3306}/oauth2?characterEncoding=utf8
    username: ${MYSQL_SERVER_USERNAME:root}
    password: ${MYSQL_SERVER_PASSWORD:wrongpwd}
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


#  rabbitmq:
#    host: 192.168.3.25
#    port: 5672
#    username: test
#    password: test123
  sleuth:
    sampler:
      percentage: 1
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
    web:
      client:
        enabled: true #web开启sleuth功能
      
  zipkin:
    base-url: http://${ZIPKIN_SERVER:zipkin-server}:9411      
  

 

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #默认：（方法上记得要加上@HystrixCommand，否则无效）
#          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true 
              
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  #https://github.com/spring-cloud/spring-cloud-security/issues/61
  http:
    client:
      enabled: true  



#HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        #include: hystrix.stream, info, health
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
      #base-path: actuator //by default

#  security:
#    enabled: false
#  context-path: /mgmt


turbine:
  app-config: service-a,service-b
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream  
    
logging:
  level:
    root: INFO
    org.springframework: INFO   